### ISSUE TITLE
Digging on Speed

### ISSUE THREAD

**Issue by davqvist** [Macrophage001/Dig#1]
MC 1.12.1
Forge 2485
Dig 1.1.7

Alright this is hard to explain, but since the new update, it is like I am digging on speed/with haste. I did a small test to make sure it is not a mod interaction and even though I defined a durability of the grass block of 10, it took only 2-3 digs until it was broken.

Script: https://pastebin.com/yjB68RTi but you can remove the Botania entries and try it with only vanilla.

Thanks for making an issue tracker btw.

**Comment by Macrophage001** [comment]
Yeah, that was a silly mistake on my part. It should be fixed in the latest release.
