### ISSUE TITLE
Placing Fake Blocks

### ISSUE THREAD

**Issue by davqvist** [Macrophage001/Dig#2]
Forge 2485
MC 1.12.1
Dig 1.1.9

I found a huge bug. If you place a block while holding shift, it places a fake block. What I mean with that is that it it renders and seems to be there but isn't actually (for the server). If you place another block in its place the original block gets now deleted and is gone, meaning that Dig actually deletes items.

To test this the easiest, make an instance with The One Probe, one other content mod (I used Embers for the example) and Dig. Then cheat in a block from that content mod (I tested with Ashen Brick Stairs) and shift place it. The One Probe now shows the block in the overlay but states the mod as Minecraft, instead of the actual mod (in my case Embers). You can compare by placing the block without pressing shift. Then you just take dirt and place it on the block you placed, deleting the original block.

That bug bugs me since over a month, but just now found out that it is Dig causing it.

**Comment by Macrophage001** [comment]
Wow, that was such a silly bug on my part. Fixed in latest version.

**Comment by Macrophage001** [comment]
Also, it seems that I've inadvertently fixed that other issue regarding the Botania grasses not working. That had me stumped for a good long while. Seems like it was an issue regarding checking to see whether the item in the player's hand was a block or not.

**Comment by davqvist** [comment]
Excellent timing on your part. That makes me happy, made my day.

**Comment by Macrophage001** [comment]
Thank you, I'm sorry it took so long, it really had me stumped -_-''
