### ISSUE TITLE
Doesn't work on server

### ISSUE THREAD

**Issue by davqvist** [Macrophage001/Dig#3]
Okay, mod is now totally working perfectly since last update. So I decided to invite modpack alpha testers and made a server. Unfortunately the mod doesn't work at all on the server. Not sure what else to tell you. Also it messes with other mods tools as well that need shift right clicking like before the last update which also means I had to disable it. Can you please investigate? Would be very much appreciated.

Dig 1.1.10
Forge 2485
MC 1.12.1
(will switch to 1.12.2 in the next days)

**Comment by Macrophage001** [comment]
Ok, I'm going to look into it when I get home from work today. Is there any more information you can provide? Do you receive errors or warnings when that occurs?

**Comment by Macrophage001** [comment]
Fixed in the latest release.

**Comment by davqvist** [comment]
Awesome, thanks for the quick fix, will test tomorrow.

**Comment by davqvist** [comment]
Haven't tested on server yet, but in SP Tools that need shift click don't work anymore. Or do I NEED to add them to the whitelist now?

**Comment by Macrophage001** [comment]
There is only a blacklist for items that you don't want to be used by my mod. If you don't want them to work with Dig then place them in the blacklist. I've made some changes on my end, hopefully it's fixed in latest release.

**Comment by davqvist** [comment]
So I tested now again, blacklisting tools works fine, but still it doesn't work on the server. I couldn't find anything in the log. Not sure what I can do to help you tracking the problem down. The only thing I can think of right now, is to do a localhost server with just Dig to at least test if it might be a mod interaction. Will report back shortly.

**Comment by Macrophage001** [comment]
Hmm, well that's odd. I've been working on it some more these past couple a days. Will post latest version tonight when I get back from work and see if that works.

**Comment by davqvist** [comment]
Thanks very much, couldn't do the test yet, sorry.

**Comment by Macrophage001** [comment]
No worries. Lemme know if this latest version fixes it =)

**Comment by davqvist** [comment]
Sorry, was on a dev break, tested now on Forge 2556 (1.12.2) and it still doesn't work on a server.
