### ISSUE TITLE
Is it possible to specify multiple outputs at different chances for the same block/tool?

### ISSUE THREAD

**Issue by Dragnier** [Macrophage001/Dig#5]
For example, can I make it so that dirt drops 2-3 different things at different rates with the same durability? If so, how would I go about doing the config for that? If not, is there any chance that could be added?

**Comment by Macrophage001** [comment]
Yes you can. The block's durability is determined by the first one that's defined. So if you make a resource where the block's durability is N, then make another resource using the same parent block, the durability will remain N but it will also have a chance to drop the new resource as well determined by what you put in for the drop chance. I hope that makes sense and helps you out.

**Comment by Dragnier** [comment]
You might think about adding this description to the wiki page.

**Comment by Macrophage001** [comment]
With the use of JSON now for defining blocks and mobs, I feel like this might be easier to understand hopefully.
