### ISSUE TITLE
[Suggestion] JEI integration to show dig drops

### ISSUE THREAD

**Issue by Dragnier** [Macrophage001/Dig#6]
Is there any way you could tie into JEI to create a way for people to see the drops from various block/tool combos? Preferably without showing the percentage chances, just what _can_ drop?

I'm in the process of making a skyblock modpack that relies on your mod to get the basic resources going instead of Ex Nihilo sieves and it would be useful to have this as a feature.

**Comment by Macrophage001** [comment]
Sure, I'm going to take a look at the JEI API and see how I can implement this when I get home.

**Comment by Macrophage001** [comment]
I'm late as all hell and am sorry but....I finally got that devilish JEI implemented in the 1.15.2 version. Although it's not as well defined as I'd like at the moment.
