### ISSUE TITLE
java.lang.NullPointerException while shift right-clicking

### ISSUE THREAD

**Issue by DatrixTHLK** [Macrophage001/Dig#7]
Minecraft 1.12.2
Forge: 14.23.3.2689-2691
Dig: 1.1.16
Crash Log: https://paste.dimdev.org/ewofekeyof.txt

Hi,
The minor crash issue happened as I was shift + right-clicking any block with the tool specified within the config file. This is all the info I know about at the moment.  My [config file](https://paste.dimdev.org/adinugobew.md) will be included in case the issue happened because of me.

Just to specify the mod in question that helped find the error is called [Vanilla Fix](https://minecraft.curseforge.com/projects/vanillafix). If you need any help ask @Runemoro.

**Comment by Dragnier** [comment]
I think this is caused by trying to dig a block that is not defined to have any dig functionality.. For example, when you are spam digging a block and then wind up clicking on the block below or behind it once the defined one breaks. The dig function should probably check if the block clicked is defined first before checking other things just to prevent this error.

**Comment by DatrixTHLK** [comment]
What you say makes sense. I'm going to guess that if I specified a block to, when digging it, have an ore or fish that isn't in my mod list or could have been removed from my mod list after specifying that type of ore or fish then that could be the issue?

**Comment by DatrixTHLK** [comment]
Oh, I see the spam is self caused. Has there been any update for this issue though?

**Comment by Dragnier** [comment]
Given that the last commit was around two years ago and no responses, I would say no and probably will never be fixed.

**Comment by DatrixTHLK** [comment]
Oh well...

**Comment by Macrophage001** [comment]
Well, I am back and I apologize for not paying greater attention. I'm going to be correcting that from now on.
