### ISSUE TITLE
Minecraft failed to start

### ISSUE THREAD

**Issue by DatrixTHLK** [Macrophage001/Dig#9]
Hi,

I don't know how to explain this error. I have geolosys and it add in new ores which were added to Underground biomes stone textures. I added each stones ores into individual stone ds files so I could easily tell which stone might be causing issues with the game or if I misspelled an ore or mod.
Minecraft: 1.12.2
Forge: 14.23.5.2836
Dig: 1.1.16_1.12.1
Crash Log: https://paste.dimdev.org/uxiruyagat.mccrash
It worked fine until just recently.

I know you haven't worked on this mod since almost two years ago. I'd hate to have to use an alternative mod just to bypass this issue because this mod is really easy to understand and work with. If there isn't a response within a week, then I will regrettably have to look elsewhere.

Thanks,

Datrix/PoisonShark

**Comment by Macrophage001** [comment]
Because I was fool and didn't read this sooner. I'll try and be more attentive from now on.
